import type { Product, ProductCategory } from "@/modules/catalog/types";
import { isProductCategory } from "@/modules/catalog/types";

export const seedProducts: Product[] = [
  {
    id: "p9",
    slug: "317-shitbox-certified-blue",
    name: "317 Shitbox Certified Sticker — Blue",
    price: 15,
    priceCents: 1500,
    category: "stickers",
    tagline: "Certified. Approved. 317.",
    description:
      "Die-cut “Certified Approved 317 Shitbox” sticker in light blue. In-stock Greenfield Street Scene drop — laptop, toolbox, water bottle, or mirror ready. Ships from Greenfield, Indiana.",
    tags: ["sticker", "317", "shitbox", "indiana", "greenfield", "gift", "in-stock"],
    colors: ["Light Blue"],
    featured: true,
    vibe: "317 shitbox",
    image: "/products/317-shitbox-blue.png",
  },
  {
    id: "p10",
    slug: "317-shitbox-certified-black",
    name: "317 Shitbox Certified Sticker — Black",
    price: 15,
    priceCents: 1500,
    category: "stickers",
    tagline: "Black ink. Zero excuses.",
    description:
      "Die-cut “Certified Approved 317 Shitbox” sticker in black and white. In-stock Greenfield Street Scene drop — same stamp energy, high-contrast finish. Ships from Greenfield, Indiana.",
    tags: ["sticker", "317", "shitbox", "indiana", "greenfield", "gift", "in-stock"],
    colors: ["Black / White"],
    featured: true,
    vibe: "317 shitbox",
    image: "/products/317-shitbox-black.png",
  },
  {
    id: "p1",
    slug: "lot-lights-tee",
    name: "Lot Lights Tee",
    price: 34,
    priceCents: 3400,
    category: "tees",
    tagline: "Sodium glow. Cold concrete.",
    description:
      "Heavyweight boxy tee for late lots and early mornings. Soft wash black with amber lot-light print on the back.",
    tags: ["night", "casual", "everyday", "meet"],
    colors: ["Asphalt Black", "Bone"],
    featured: true,
    vibe: "night lot",
  },
  {
    id: "p2",
    slug: "street-stripe-hoodie",
    name: "Street Stripe Hoodie",
    price: 68,
    priceCents: 6800,
    category: "hoodies",
    tagline: "Warm when the lot goes quiet.",
    description:
      "French terry hoodie with a single racing stripe down the sleeve. Built for cool nights between pullouts.",
    tags: ["cold", "night", "layered", "premium"],
    colors: ["Charcoal", "Oxblood"],
    featured: true,
    vibe: "cold night",
  },
  {
    id: "p3",
    slug: "grid-cap",
    name: "Grid Cap",
    price: 28,
    priceCents: 2800,
    category: "hats",
    tagline: "Low profile. High mileage.",
    description:
      "Structured five-panel with tonal embroidery. Sits clean with sunglasses or a helmet bag.",
    tags: ["day", "casual", "everyday", "sun"],
    colors: ["Black", "Stone"],
    featured: true,
    vibe: "day meet",
  },
  {
    id: "p4",
    slug: "meet-map-sticker-pack",
    name: "Meet Map Sticker Pack",
    price: 12,
    priceCents: 1200,
    category: "stickers",
    tagline: "Mark the spots that mattered.",
    description:
      "Eight die-cut stickers of lot maps, tire marks, and Greenfield Street Scene marks. Laptop, toolbox, or mirror ready.",
    tags: ["cheap", "gift", "collector", "everyday"],
    colors: ["Multi"],
    featured: false,
    vibe: "collector",
  },
  {
    id: "p5",
    slug: "pit-lane-longsleeve",
    name: "Pit Lane Longsleeve",
    price: 42,
    priceCents: 4200,
    category: "tees",
    tagline: "Sleeve graphics that catch the flash.",
    description:
      "Relaxed longsleeve with reflective pit-lane marks on both sleeves. Looks sharp under garage lights.",
    tags: ["night", "photo", "layered"],
    colors: ["Ink", "Fog"],
    featured: false,
    vibe: "photo night",
  },
  {
    id: "p6",
    slug: "torque-keychain",
    name: "Torque Keychain",
    price: 18,
    priceCents: 1800,
    category: "accessories",
    tagline: "Small weight. Loud identity.",
    description:
      "Machined aluminum key tag with Greenfield Street Scene stamp. Survives pocket lint and parking lot abuse.",
    tags: ["gift", "everyday", "cheap", "accessory"],
    colors: ["Raw Aluminum"],
    featured: false,
    vibe: "daily carry",
  },
  {
    id: "p7",
    slug: "afterhours-crew",
    name: "Afterhours Crew",
    price: 58,
    priceCents: 5800,
    category: "hoodies",
    tagline: "For the last cars left.",
    description:
      "Cropped crewneck with oversized back print. Soft handfeel, zero fluff branding on the chest.",
    tags: ["night", "premium", "layered", "photo"],
    colors: ["Midnight", "Rust"],
    featured: true,
    vibe: "afterhours",
  },
  {
    id: "p8",
    slug: "lane-marker-beanie",
    name: "Lane Marker Beanie",
    price: 24,
    priceCents: 2400,
    category: "hats",
    tagline: "Yellow line energy.",
    description:
      "Rib knit beanie with a single embroidered lane marker. Winter meets and empty freeways.",
    tags: ["cold", "winter", "night"],
    colors: ["Black / Amber"],
    featured: false,
    vibe: "winter meet",
  },
];

export type { Product, ProductCategory };
export { isProductCategory };
