import type { Meet } from "@/modules/meets/types";

export const seedMeets: Meet[] = [
  {
    id: "m1",
    slug: "sodium-lot-saturdays",
    name: "Sodium Lot Saturdays",
    city: "Los Angeles, CA",
    date: "Every Saturday",
    time: "9:00 PM – 1:00 AM",
    venue: "Industrial lot, Arts District",
    vibe: "Night cruise · street · community",
    description:
      "Weekly night lot under sodium lights. Clean builds, loud conversations, no burnout circus. Merch table opens at 9.",
    tags: ["night", "weekly", "street", "la", "casual"],
    capacity: "Open lot",
    featured: true,
  },
  {
    id: "m2",
    slug: "sunrise-grid",
    name: "Sunrise Grid",
    city: "Phoenix, AZ",
    date: "Aug 2, 2026",
    time: "5:30 AM – 8:30 AM",
    venue: "Desert overlook staging area",
    vibe: "Golden hour · photo · calm",
    description:
      "Early light meet for photographers and quiet engines. Coffee first, photos second, roll out before heat.",
    tags: ["day", "photo", "calm", "phoenix", "sunrise"],
    capacity: "120 cars",
    featured: true,
  },
  {
    id: "m3",
    slug: "coast-line-cruise",
    name: "Coast Line Cruise",
    city: "San Diego, CA",
    date: "Aug 16, 2026",
    time: "6:00 PM – 10:00 PM",
    venue: "Meet at Harbor staging, cruise PCH",
    vibe: "Cruise · coastal · social",
    description:
      "Harbor meetup into a coastal group cruise. Bring a friend, bring patience, leave ego at home.",
    tags: ["cruise", "evening", "social", "sd", "coast"],
    capacity: "80 cars",
    featured: true,
  },
  {
    id: "m4",
    slug: "warehouse-warmup",
    name: "Warehouse Warmup",
    city: "Dallas, TX",
    date: "Sep 6, 2026",
    time: "7:00 PM – 11:00 PM",
    venue: "Private warehouse yard",
    vibe: "Indoor-outdoor · builds · vendor",
    description:
      "Covered yard meet with vendor booths, build talks, and Greenfield Street Scene drop preview. Ticketed entry keeps it clean.",
    tags: ["night", "ticketed", "vendors", "dallas", "builds"],
    capacity: "200 tickets",
    featured: false,
  },
  {
    id: "m5",
    slug: "frost-lot",
    name: "Frost Lot",
    city: "Denver, CO",
    date: "Oct 11, 2026",
    time: "8:00 PM – 12:00 AM",
    venue: "Highland industrial lot",
    vibe: "Cold weather · night · layers",
    description:
      "Cold-air night meet for people who still show up when the temperature drops. Hoodies recommended.",
    tags: ["night", "cold", "winter", "denver", "casual"],
    capacity: "Open lot",
    featured: false,
  },
];
