import type { Meet } from "@/modules/meets/types";

/** Local meets centered on Greenfield, Indiana + nearby Indy metro. */
export const seedMeets: Meet[] = [
  {
    id: "m1",
    slug: "courthouse-square-nights",
    name: "Courthouse Square Nights",
    city: "Greenfield, IN",
    date: "Every Saturday",
    time: "7:00 PM – 10:30 PM",
    venue: "Downtown Greenfield square staging",
    vibe: "Night lot · hometown · community",
    description:
      "Weekly Greenfield night meet. Clean builds, good music, respect the square. Merch table opens at 7.",
    tags: ["night", "weekly", "street", "greenfield", "indiana", "casual"],
    capacity: "Open lot",
    featured: true,
  },
  {
    id: "m2",
    slug: "sunrise-on-us-40",
    name: "Sunrise on US-40",
    city: "Greenfield, IN",
    date: "Aug 2, 2026",
    time: "6:00 AM – 8:30 AM",
    venue: "East side staging off US-40 / Main Street corridor",
    vibe: "Golden hour · photo · calm",
    description:
      "Early light meet for photographers and quiet engines. Coffee first, photos second, home before the heat.",
    tags: ["day", "photo", "calm", "greenfield", "indiana", "sunrise"],
    capacity: "80 cars",
    featured: true,
  },
  {
    id: "m3",
    slug: "hancock-county-cruise",
    name: "Hancock County Cruise",
    city: "Greenfield, IN",
    date: "Aug 16, 2026",
    time: "6:00 PM – 10:00 PM",
    venue: "Meet at Riley Park lot, cruise the county loop",
    vibe: "Cruise · backroads · social",
    description:
      "Hometown meetup into a Hancock County group cruise. Bring a friend, bring patience, leave ego at home.",
    tags: ["cruise", "evening", "social", "greenfield", "indiana", "hancock"],
    capacity: "60 cars",
    featured: true,
  },
  {
    id: "m4",
    slug: "indy-eastside-warmup",
    name: "Indy Eastside Warmup",
    city: "Indianapolis, IN",
    date: "Sep 6, 2026",
    time: "7:00 PM – 11:00 PM",
    venue: "Eastside industrial yard (ticketed)",
    vibe: "Indoor-outdoor · builds · vendor",
    description:
      "Bigger Indy-side meet with vendor booths, build talks, and a Greenfield Street Scene drop preview. Easy drive from Greenfield.",
    tags: ["night", "ticketed", "vendors", "indianapolis", "indiana", "builds"],
    capacity: "200 tickets",
    featured: false,
  },
  {
    id: "m5",
    slug: "frost-lot-greenfield",
    name: "Frost Lot",
    city: "Greenfield, IN",
    date: "Oct 11, 2026",
    time: "7:00 PM – 10:00 PM",
    venue: "North industrial lot",
    vibe: "Cold weather · night · layers",
    description:
      "Midwest cold-air night meet for people who still show up when the temperature drops. Hoodies recommended.",
    tags: ["night", "cold", "winter", "greenfield", "indiana", "casual"],
    capacity: "Open lot",
    featured: false,
  },
];
